import { type Ref } from "vue";
import type { Card, RenderedCardMode, RoundResultPlayer } from "@/types/game";
import type { useRoom } from "./useRoom";
type Room = ReturnType<typeof useRoom>;
type SettlementGroupBlock = {
    id: string;
    cards: Card[];
    badge?: string;
    label?: string;
    tone: "meld" | "fish" | "public" | "strong";
};
type SettlementOptions = Pick<Room, "state" | "huResult" | "roundResult" | "players" | "mySeatId" | "activeRoomId" | "nextRound" | "returnLobby" | "connect" | "leaveRoom" | "joinError"> & {
    isEnded: Readonly<Ref<boolean>>;
    isHost: Readonly<Ref<boolean>>;
    resolvedOwnCardMode: Readonly<Ref<RenderedCardMode>>;
    resolvedTableCardMode: Readonly<Ref<RenderedCardMode>>;
    entryName: Ref<string>;
    globalError: Ref<string>;
    enteredFrontLobby: Ref<boolean>;
    handleLeaveRoom: () => Promise<void>;
    generateRandomNickname: () => string;
    cardLabel: (card: Card) => string;
};
/** Public settlement presentation and receipt-locked transitions; scoring stays server-owned. */
export declare function useSettlement({ state, huResult, roundResult, players, mySeatId, activeRoomId, nextRound, returnLobby, connect, leaveRoom, joinError, isEnded, isHost, resolvedOwnCardMode, resolvedTableCardMode, entryName, globalError, enteredFrontLobby, handleLeaveRoom, generateRandomNickname, cardLabel }: SettlementOptions): {
    settlementPanelRef: Ref<HTMLElement | null, HTMLElement | null>;
    confirmingNextRound: Ref<boolean, boolean>;
    nextRoundTriggerRef: Ref<HTMLButtonElement | null, HTMLButtonElement | null>;
    nextRoundDialogRef: Ref<HTMLElement | null, HTMLElement | null>;
    nextRoundCancelRef: Ref<HTMLButtonElement | null, HTMLButtonElement | null>;
    confirmingReturnLobby: Ref<boolean, boolean>;
    returnLobbyTriggerRef: Ref<HTMLButtonElement | null, HTMLButtonElement | null>;
    returnLobbyDialogRef: Ref<HTMLElement | null, HTMLElement | null>;
    returnLobbyCancelRef: Ref<HTMLButtonElement | null, HTMLButtonElement | null>;
    settlementTransitionPending: Ref<("next_round" | "return_lobby") | null, ("next_round" | "return_lobby") | null>;
    quickRematchPending: Ref<boolean, boolean>;
    endPanelTitle: import("vue").ComputedRef<"胡牌结算" | "流局结算">;
    derivedWinnerId: import("vue").ComputedRef<string>;
    participantDisplayName: (player: {
        name: string;
        isConfiguredBot?: boolean;
    }) => string;
    roundOutcomeText: import("vue").ComputedRef<string>;
    settlementPlayers: import("vue").ComputedRef<RoundResultPlayer[]>;
    settlementReady: import("vue").ComputedRef<boolean>;
    isCumulativeSettlement: import("vue").ComputedRef<boolean>;
    settlementRoundNumber: import("vue").ComputedRef<number>;
    mySettlementPlayer: import("vue").ComputedRef<RoundResultPlayer | null>;
    orderedSettlementPlayers: import("vue").ComputedRef<RoundResultPlayer[]>;
    remainingDeckPreview: import("vue").ComputedRef<Card[]>;
    settlementGroupBlocks: (player: RoundResultPlayer) => SettlementGroupBlock[];
    settlementHandBlocks: (player: RoundResultPlayer) => SettlementGroupBlock[];
    signedScore: (value: number) => string;
    scoreToneClass: (value: number) => string;
    isSettlementWinner: (player: RoundResultPlayer) => boolean;
    settlementHandCardMode: (playerId: string) => RenderedCardMode;
    winnerSettlementPlayer: import("vue").ComputedRef<RoundResultPlayer | null>;
    huCalculationLines: import("vue").ComputedRef<{
        label: string;
        key: string;
        count: number;
        unit: number;
        total: number;
    }[]>;
    winnerPerOpponentScore: import("vue").ComputedRef<number>;
    settlementScoreLines: (player: RoundResultPlayer) => Array<{
        key: string;
        label: string;
        total: number;
    }>;
    endSummary: import("vue").ComputedRef<string>;
    roundDealerCard: import("vue").ComputedRef<Card | null>;
    showEndPanel: import("vue").ComputedRef<boolean>;
    clearSettlementTransitionPending: () => void;
    requestNextRound: () => Promise<void>;
    rematchQuickTable: () => Promise<void>;
    returnPracticeToModeSelection: () => Promise<void>;
    cancelNextRound: () => void;
    confirmNextRound: () => void;
    trapNextRoundFocus: (event: KeyboardEvent) => void;
    requestReturnLobby: () => Promise<void>;
    cancelReturnLobby: () => void;
    confirmReturnLobby: () => void;
    trapReturnLobbyFocus: (event: KeyboardEvent) => void;
};
export {};
